### PR TITLE
another api variation

### PR DESCRIPTION
**Pull request by Guria**
haven't tested it yet. just pushed to review what already done.

manage modules scoped initial state
accept modules as object
use object key as module name
provide init method with registered module name
allow root Component to be returned from init method

### CODE REVIEW

**Comment by garth** [comment]
I really like moving the modules to a hash, that makes things a lot simpler. Tried to merge but had major  conflicts.

Also had a discussion with Christian and Brian who had some good suggestions.

I think that we can remove all exports from a module except the component, maybe we can provide a wrapper around the given controller so that we can set a namespace for signals and for items added to the cerebral.services.

"Imagine the "home" module of that app being a "cerebral-module". The home page basically just has a form for registering your email. So it exposes a signal for updating the input, clicking the button and a loading state for saving the email. This state and signals are hooked on to the namespace "homeModule", so "homeModule.inputChanged", "homeModule.buttonClicked" etc. The module also exposes a Component that you choose when and where to render. Inside the Component are the input, the button and whatever else. Using the signals exposed by the module :smile: So we could build all sorts of amazing stuff with this. Everything from a complete UI library, to mail forms, pouchdb, debuggers, widgets etc."

**Comment by Guria** [comment]
I can make a rebase if you accepts all that I've done

**Comment by Guria** [comment]
I have rebased and made another round of "improvements" :)
I am going to test this setup on project yo have shared recently

**Comment by Guria** [comment]
Cerebral with `controller.extends` is out.Will update to use it

**Pull request merged**
